package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Categorias_ventana extends CssLayout {
	protected HorizontalLayout menu;
	protected Button principal;
	protected Button micuenta;
	protected Button lista_usuarios;
	protected Button categorias;
	protected CssLayout listacategorias;

	public Categorias_ventana() {
		Design.read(this);
	}
}
