package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Datos_Admin_ventana extends VerticalLayout {
	protected Image avatar;
	protected Button editaravatar;
	protected TextField url;
	protected Label nombre;
	protected Label apellido;
	protected Label apodo;
	protected Label anio;
	protected Label email;
	protected Label contrasenia;
	protected Label repetircontrasenia;
	protected Button modificar;

	public Datos_Admin_ventana() {
		Design.read(this);
	}
}
