package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mi_perfil_ventana extends CssLayout {
	protected VerticalLayout menu;
	protected Button principal;
	protected Button micuenta;
	protected Button videos_subidos;
	protected Button mis_listas;
	protected Button suscripciones;
	protected VerticalLayout mi_cuenta;
	protected VerticalLayout cerrar_sesion;

	public Mi_perfil_ventana() {
		Design.read(this);
	}
}
