package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Registrarse_ventana extends VerticalLayout {
	protected TextField nombre;
	protected TextField apellidos;
	protected TextField apodo;
	protected ComboBox<java.lang.String> edad;
	protected TextField email;
	protected TextField contrasenia;
	protected TextField confirmar;
	protected Button cancelarBoton;
	protected Button registrarseBoton;

	public Registrarse_ventana() {
		Design.read(this);
	}
}
