package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Subir_video_ventana extends VerticalLayout {
	protected Button subir_video;
	protected Button volver;
	protected TextField titulo;
	protected Button miniatura;
	protected CheckBox deshabilitarCom;
	protected TextArea descripcion;
	protected TextArea etiquetas;
	protected ComboBox<java.lang.String> categoriaCombo;
	protected ComboBox<java.lang.String> aniadirALista;

	public Subir_video_ventana() {
		Design.read(this);
	}
}
