package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Subir_video_ventana extends HorizontalLayout {
	protected TextField titulo;
	protected TextField miniatura;
	protected ComboBox<java.lang.String> lista;
	protected CheckBox comentarios;
	protected HorizontalLayout categoria1;
	protected TextField url;
	protected TextArea descripcion;
	protected TextArea etiquetas;
	protected Button subir;
	protected Button atras;

	public Subir_video_ventana() {
		Design.read(this);
	}
}
