package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Video_busqueda_ventana extends HorizontalLayout {
	protected HorizontalLayout videoBusqueda;
	protected Image miniatura;
	protected Label titulo;
	protected Label autor;
	protected Label fechasubida;
	protected Label numVisu;
	protected Label numMeGusta;

	public Video_busqueda_ventana() {
		Design.read(this);
	}
}
