package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Vista_perfil_Registrado_ventana extends CssLayout {
	protected VerticalLayout videosSubidos;
	protected VerticalLayout listas_reproduccion;
	protected VerticalLayout suscripciones;
	protected VerticalLayout seguidores;

	public Vista_perfil_Registrado_ventana() {
		Design.read(this);
	}
}
