package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Video;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Vista_video_comun_ventana extends VerticalLayout {
	protected Button volver;
	protected Video video;
	protected Label titulo;
	protected Label fechaVideo;
	protected Label visualizaciones;
	protected Label megusta;
	protected Label categoria;
	protected VerticalLayout avatar;
	protected TextArea descripcion;

	public Vista_video_comun_ventana() {
		Design.read(this);
	}
}
