package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Video;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Visualizacion_video_ventana extends VerticalLayout {
	protected Button volver;
	protected Video video;
	protected Label titulo;
	protected HorizontalLayout botonesOpciones;
	protected Button eliminarVideo;
	protected Button meGusta;
	protected Button descargar;
	protected Label nombre;
	protected HorizontalLayout avatar;
	protected Label fecha;
	protected Label visualizaciones;
	protected Label categoria;
	protected HorizontalLayout aniadirALista;
	protected ComboBox<java.lang.String> comboBox;
	protected Button aniadeALista;
	protected TextArea descripcion;
	protected VerticalLayout escribirComentario;
	protected VerticalLayout listaComentarios;

	public Visualizacion_video_ventana() {
		Design.read(this);
	}
}
